---
title: "LandR_speciesParameters"
author: ""
date: "17 September 2019"
output: pdf_document
---

# Overview

Provide an overview of what the module does / how to use the module.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
library(SpaDES)
library(SpaDES.experiment)

setPaths(modulePath = file.path("../"))
getPaths() # shows where the 4 relevant paths are

times <- list(start = 0, end = 10)

modules <- list("LandR_speciesParameters", 'PSP_Clean')
objects <- list()
inputs <- list()
outputs <- list()

parameters <- list(LandR_speciesParameters = 
                     list(GAMMiterations = 2, 
                          GAMMknots = list(
                            "Abie_bal" = 3,
                            "Abie_las" = 3,
                            "Betu_pap" = 3,
                            "Lari_lar" = 4,
                            "Pice_eng" = 4,
                            "Pice_gla" = 3,
                            "Pice_mar" = 4,
                            "Pinu_ban" = 3,
                            "Pinu_con" = 4, 
                            "Popu_tre" = 4,
                            "Pseu_men" = 3),
                          minimumPlotsPerGamm = 40,
                          constrainMortalityShape = list(
                            "Abie_bal" = c(15,25),
                            "Abie_las" = c(15,25),
                            "Betu_pap" = c(15,25),
                            "Lari_lar" = c(20,25),
                            "Pice_eng" = c(15,25),
                            "Pice_gla" = c(15,25),
                            "Pice_mar" = c(15,25),
                            "Pinu_ban" = c(15,25),
                            "Pinu_con" = c(15,25), 
                            "Popu_tre" = c(15,25),
                            "Pseu_men" = c(20,25)
                          ),
                          quantileAgeSubset = list(
                            "Abie_bal" = 95, #N = 43 w/ 95 subset
                            "Abie_las" = 95, #N = 250 '' 
                            "Betu_pap" = 95, #N = 96
                            "Lari_lar" = 95, #N = 45
                            "Pice_eng" = 95, #N = 130
                            "Pice_gla" = 95, #N = 1849
                            "Pice_mar" = 95, #N = 785
                            "Pinu_ban" = 95, #N = 603
                            "Pinu_con" = 99, # N = 3172, 99 not an improvement. Maybe 97
                            "Popu_tre" = 99, # N = 1997, trying 99
                            "Pseu_men" = 99 # N = 2797, 99 is an improvement
                          )
                     ))


mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)

mySimOut <- spades(mySim)


```


# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("LandR_speciesParameters", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

